const testNames = [
  { firstName: 'Emily', lastName: 'William' },
  { firstName: 'Michael', lastName: 'Lee' },
  { firstName: 'Sarah', lastName: 'Johnson' },
  { firstName: 'David', lastName: 'Chen' },
  { firstName: 'Olivia', lastName: 'William' },
  { firstName: 'William', lastName: 'Kim' },
  { firstName: 'Sophia', lastName: 'Singh' },
  { firstName: 'James', lastName: 'Rodriguez' },
  { firstName: 'Ava', lastName: 'Patel' },
  { firstName: 'Benjamin', lastName: 'Garcia' },
  { firstName: 'Isabella', lastName: 'Nguyen' },
  { firstName: 'Ethan', lastName: 'Lee' },
  { firstName: 'Mia', lastName: 'Wilson' },
  { firstName: 'Alexander', lastName: 'William' },
  { firstName: 'Charlotte', lastName: 'Hernandez' },
  { firstName: 'Liam', lastName: 'Gonzalez' },
  { firstName: 'Emma', lastName: 'Gomez' },
  { firstName: 'Noah', lastName: 'Perez' },
  { firstName: 'Avery', lastName: 'Ramirez' },
  { firstName: 'Jacob', lastName: 'Turner' },
  { firstName: 'Abigail', lastName: 'Williams' },
  { firstName: 'Elijah', lastName: 'Hall' },
  { firstName: 'Mila', lastName: 'Flores' },
  { firstName: 'Evelyn', lastName: 'Morales' },
  { firstName: 'Logan', lastName: 'Collins' },
];

module.exports = { testNames };
